<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return Inertia::render('welcome');
})->name('home');

const users = [
    [
        'id' => 1,
        'name' => 'Auto Elite Dealers',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'contact@autoelite.com',
            'phone' => '+1 (555) 123-4567',
            'address' => '123 Motor City Dr, Detroit, MI'
        ],
        'total_listings' => 42,
        'pending' => 3,
        'sold' => 15,
        'status' => 'active',
        'last_login' => '2023-11-15T09:23:45Z'
    ],
    [
        'id' => 2,
        'name' => 'John Smith',
        'type' => 'private',
        'contact_info' => [
            'email' => 'john.smith@gmail.com',
            'phone' => '+1 (555) 987-6543'
        ],
        'total_listings' => 5,
        'pending' => 1,
        'sold' => 2,
        'status' => 'active',
        'last_login' => '2023-11-14T14:12:33Z'
    ],
    [
        'id' => 3,
        'name' => 'Luxury Motors',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'sales@luxurymotors.com',
            'phone' => '+1 (555) 234-5678',
            'address' => '456 Premium Ave, Beverly Hills, CA'
        ],
        'total_listings' => 28,
        'pending' => 2,
        'sold' => 8,
        'status' => 'suspended',
        'last_login' => '2023-10-30T11:45:21Z'
    ],
    [
        'id' => 4,
        'name' => 'Sarah Johnson',
        'type' => 'private',
        'contact_info' => [
            'email' => 'sarahj82@yahoo.com',
            'phone' => '+1 (555) 345-6789'
        ],
        'total_listings' => 3,
        'pending' => 0,
        'sold' => 1,
        'status' => 'active',
        'last_login' => '2023-11-15T07:32:10Z'
    ],
    [
        'id' => 5,
        'name' => 'Truck Nation',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'info@trucknation.com',
            'phone' => '+1 (555) 456-7890',
            'address' => '789 Heavy Duty Rd, Dallas, TX'
        ],
        'total_listings' => 37,
        'pending' => 5,
        'sold' => 12,
        'status' => 'active',
        'last_login' => '2023-11-14T16:45:22Z'
    ],
    [
        'id' => 6,
        'name' => 'Mike Rodriguez',
        'type' => 'private',
        'contact_info' => [
            'email' => 'mike.rodriguez@outlook.com',
            'phone' => '+1 (555) 567-8901'
        ],
        'total_listings' => 7,
        'pending' => 2,
        'sold' => 3,
        'status' => 'pending_verification',
        'last_login' => '2023-11-10T12:15:43Z'
    ],
    [
        'id' => 7,
        'name' => 'EV Specialists',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'support@evspecialists.com',
            'phone' => '+1 (555) 678-9012',
            'address' => '321 Electric Ave, San Francisco, CA'
        ],
        'total_listings' => 19,
        'pending' => 1,
        'sold' => 6,
        'status' => 'active',
        'last_login' => '2023-11-15T08:12:54Z'
    ],
    [
        'id' => 8,
        'name' => 'Emily Wilson',
        'type' => 'private',
        'contact_info' => [
            'email' => 'emily.wilson@gmail.com',
            'phone' => '+1 (555) 789-0123'
        ],
        'total_listings' => 2,
        'pending' => 0,
        'sold' => 0,
        'status' => 'inactive',
        'last_login' => '2023-09-22T18:32:11Z'
    ],
    [
        'id' => 7,
        'name' => 'EV Specialists',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'support@evspecialists.com',
            'phone' => '+1 (555) 678-9012',
            'address' => '321 Electric Ave, San Francisco, CA'
        ],
        'total_listings' => 19,
        'pending' => 1,
        'sold' => 6,
        'status' => 'active',
        'last_login' => '2023-11-15T08:12:54Z'
    ],
    [
        'id' => 8,
        'name' => 'Emily Wilson',
        'type' => 'private',
        'contact_info' => [
            'email' => 'emily.wilson@gmail.com',
            'phone' => '+1 (555) 789-0123'
        ],
        'total_listings' => 2,
        'pending' => 0,
        'sold' => 0,
        'status' => 'inactive',
        'last_login' => '2023-09-22T18:32:11Z'
    ],
    [
        'id' => 7,
        'name' => 'EV Specialists',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'support@evspecialists.com',
            'phone' => '+1 (555) 678-9012',
            'address' => '321 Electric Ave, San Francisco, CA'
        ],
        'total_listings' => 19,
        'pending' => 1,
        'sold' => 6,
        'status' => 'active',
        'last_login' => '2023-11-15T08:12:54Z'
    ],
    [
        'id' => 8,
        'name' => 'Emily Wilson',
        'type' => 'private',
        'contact_info' => [
            'email' => 'emily.wilson@gmail.com',
            'phone' => '+1 (555) 789-0123'
        ],
        'total_listings' => 2,
        'pending' => 0,
        'sold' => 0,
        'status' => 'inactive',
        'last_login' => '2023-09-22T18:32:11Z'
    ],
    [
        'id' => 7,
        'name' => 'EV Specialists',
        'type' => 'dealer',
        'contact_info' => [
            'email' => 'support@evspecialists.com',
            'phone' => '+1 (555) 678-9012',
            'address' => '321 Electric Ave, San Francisco, CA'
        ],
        'total_listings' => 19,
        'pending' => 1,
        'sold' => 6,
        'status' => 'active',
        'last_login' => '2023-11-15T08:12:54Z'
    ],
    [
        'id' => 8,
        'name' => 'Emily Wilson',
        'type' => 'private',
        'contact_info' => [
            'email' => 'emily.wilson@gmail.com',
            'phone' => '+1 (555) 789-0123'
        ],
        'total_listings' => 2,
        'pending' => 0,
        'sold' => 0,
        'status' => 'inactive',
        'last_login' => '2023-09-22T18:32:11Z'
    ]
];;

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', function () {
        $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8
            ]
        ];

        return Inertia::render('dashboard',['data'=>$data]);
    })->name('dashboard');

    Route::get('users', function () {
        return Inertia::render('users',['data'=> users]);
    })->name('users');

    Route::get('users/edit', function () {
        $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8
            ]
        ];
        return Inertia::render('users/edit',['data'=>users,'cars'=>$data]);
    })->name('users/edit');

    Route::get('listings', function () {
                $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8
            ]
        ];
        return Inertia::render('listings',['data'=>users,'cars'=>$data]);
    })->name('listings');

    Route::get('listings/car',function(){
        $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8
            ]
        ];
        return Inertia::render('users/edit',['data'=>users,'cars'=>$data]);
    })->name('users/edit');

    Route::get('listings/car', function () {
                $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8
            ]
        ];
        return Inertia::render('listings/car',['cars'=>$data]);
    })->name('listings/car');

    Route::get('promotions', function () {
        return Inertia::render('promotions');
    })->name('promotions');

    Route::get('emp-settings', function () {
        return Inertia::render('emp-settings');
    })->name('emp-settings');

    Route::get('analytics', function () {
        return Inertia::render('analytics');
    })->name('analytics');

    Route::get('dealers', function () {
        $data = [
            [
                'id' => 1,
                'username' => 'autodealer_pro',
                'plan' => 'boosted',
                'submission_date' => '2023-10-15T09:30:00Z',
                'status' => 'active',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2022,
                'price' => 24999,
                'mileage' => 12500,
                'fuel_type' => 'Hybrid',
                'transmission' => 'Automatic',
                'color' => 'Silver',
                'body_type' => 'Sedan',
                'engine_size' => '2.5L',
                'horsepower' => 208,
                'features' => ['Leather Seats', 'Apple CarPlay', 'Blind Spot Monitoring', 'Adaptive Cruise Control'],
                'images' => ['camry_1.jpg', 'camry_2.jpg'],
                'location' => 'Los Angeles, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.7,
                'wakeel' => 'AlKasid',
                'wakeel_icon' => 'wakeel.png'
            ],
            [
                'id' => 2,
                'username' => 'truck_lover88',
                'plan' => 'free',
                'submission_date' => '2023-11-02T14:15:00Z',
                'status' => 'active',
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2021,
                'price' => 38990,
                'mileage' => 32000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Blue',
                'body_type' => 'Pickup Truck',
                'engine_size' => '3.5L V6',
                'horsepower' => 400,
                'features' => ['4WD', 'Towing Package', 'Heated Seats', 'Navigation System'],
                'images' => ['f150_1.jpg', 'f150_2.jpg'],
                'location' => 'Houston, TX',
                'seller_type' => 'Private',
                'rating' => 4.5,
                'wakeel' => 'AlKasid',
                'wakeel_icon' => 'wakeel.png'
            ],
            [
                'id' => 3,
                'username' => 'ev_enthusiast',
                'plan' => 'boosted',
                'submission_date' => '2023-11-10T10:45:00Z',
                'status' => 'pending',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'price' => 42990,
                'mileage' => 5000,
                'fuel_type' => 'Electric',
                'transmission' => 'Automatic',
                'color' => 'Red',
                'body_type' => 'Sedan',
                'battery_range' => '315 miles',
                'horsepower' => 283,
                'features' => ['Autopilot', 'Premium Sound System', 'Glass Roof', 'Wireless Charging'],
                'images' => ['tesla_1.jpg', 'tesla_2.jpg'],
                'location' => 'San Francisco, CA',
                'seller_type' => 'Dealer',
                'rating' => 4.9,
                'wakeel' => 'AlKasid',
                'wakeel_icon' => 'wakeel.png'
            ],
            [
                'id' => 4,
                'username' => 'family_cars',
                'plan' => 'free',
                'submission_date' => '2023-09-28T16:20:00Z',
                'status' => 'rejected',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2020,
                'price' => 22900,
                'mileage' => 28000,
                'fuel_type' => 'Gasoline',
                'transmission' => 'Automatic',
                'color' => 'Black',
                'body_type' => 'SUV',
                'engine_size' => '1.5L Turbo',
                'horsepower' => 190,
                'features' => ['AWD', 'Sunroof', 'Lane Keeping Assist', 'Android Auto'],
                'images' => ['crv_1.jpg', 'crv_2.jpg'],
                'location' => 'Chicago, IL',
                'seller_type' => 'Dealer',
                'rating' => 4.6,
                'rejection_reason' => 'Incomplete documentation',
                'wakeel' => 'AlKasid',
                'wakeel_icon' => 'wakeel.png'
            ],
            [
                'id' => 5,
                'username' => 'luxury_deals',
                'plan' => 'boosted',
                'submission_date' => '2023-11-05T11:10:00Z',
                'status' => 'active',
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2021,
                'price' => 52900,
                'mileage' => 18000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatic',
                'color' => 'White',
                'body_type' => 'SUV',
                'engine_size' => '3.0L',
                'horsepower' => 265,
                'features' => ['Premium Package', 'Heated Steering Wheel', 'Parking Assistant', 'Harmon Kardon Sound'],
                'images' => ['x5_1.jpg', 'x5_2.jpg'],
                'location' => 'Miami, FL',
                'seller_type' => 'Dealer',
                'rating' => 4.8,
                'wakeel' => 'AlKasid',
                'wakeel_icon' => 'wakeel.png'
            ]
        ];
        return Inertia::render('dealers',['data'=>$data]);
    })->name('dealers');
});

require __DIR__.'/settings.php';
require __DIR__.'/auth.php';
